# Generated by Django 5.1.3 on 2025-01-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('1', 'Developer'), ('2', 'Designer'), ('3', 'Manager'), ('4', 'Administrator')], max_length=255, null=True),
        ),
    ]
